[build]
publish = "."
functions = "netlify/functions"


[[headers]]
for = "/styles.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"


[[headers]]
for = "/main.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"